# PyTorch Basics Tutorial
This notebook covers fundamental PyTorch concepts including tensor creation, operations, and neural network layers.

In [3]:
!pip install torch --index-url https://download.pytorch.org/whl/cpu

Looking in indexes: https://download.pytorch.org/whl/cpu


## Imports
Import the torch library for tensor operations.

In [4]:
import torch

## Creating Tensors
A tensor is PyTorch's fundamental data structure. Here we create a 1D tensor (vector) from a Python list.

In [18]:
my_list = [1, 2, 3 , 4, 5]
my_tensor = torch.tensor(my_list, dtype=torch.float32)
my_tensor

tensor([1., 2., 3., 4., 5.])

## Tensor Properties: Shape
Check the shape of the tensor. Shape describes the dimensions and size along each dimension.

In [19]:
my_tensor.shape

torch.Size([5])

## Tensor Properties: Data Type
Check the data type of tensor elements. We used float32, which is common for neural networks.

In [20]:
my_tensor.dtype

torch.float32

## Tensor Operations: Matrix Multiplication
Create 2D tensors (matrices) and perform matrix multiplication using the @ operator.

In [24]:
my_tensor1 = torch.tensor([[1, 2, ],
                            [4, 5, ]])

my_tensor2 = torch.tensor([[5, 6, ],
                            [8, 9, ]]
                            )

print(my_tensor1 @ my_tensor2)

tensor([[21, 24],
        [60, 69]])


## Neural Network Layers
Introduce neural network building blocks. Here we create a Linear layer (fully connected) that transforms 5 input features to 3 output features.

In [29]:
import torch.nn as nn
input_tensor = torch.tensor([[1, 2, 3, 4, 5]], dtype=torch.float32)
linear_layer = nn.Linear(in_features=5, out_features=3)
output_tensor = linear_layer(input_tensor) 
output_tensor

tensor([[-2.3485,  0.6138, -2.2204]], grad_fn=<AddmmBackward0>)

A linear (fully connected) layer performs the transformation:
$$\text{output} = \text{input} \cdot \mathbf{W}^T + \mathbf{b}$$


In [30]:
linear_layer.weight

Parameter containing:
tensor([[-0.2840, -0.2452, -0.2679,  0.0188, -0.2418],
        [-0.3697, -0.1334, -0.2314,  0.0674,  0.2665],
        [ 0.2475, -0.1117, -0.3532, -0.1629, -0.0925]], requires_grad=True)

In [31]:
linear_layer.bias

Parameter containing:
tensor([ 0.3635,  0.3425, -0.0706], requires_grad=True)

#### Linear Layer: Neurons and Parameters
Understanding the structure of a neural network layer requires knowing:
- **Number of neurons (output units)**: Determines output dimension
- **Total parameters**: Number of weights and biases to learn


In [33]:
model = nn.Sequential(nn.Linear(in_features=5, out_features=3),
                      nn.Linear(in_features=3, out_features=2))


- so first layer have 3 neuron and each neuron have 5+1 parameter = 18. 
- second layer have 2 neurons and each neuron have 3+1 parameter = 8. 
- so total learnable parameter count = 26

In [34]:
total = 0
for parameter in model.parameters():
    total += parameter.numel()
print(total)

26
