# PyTorch Basics Tutorial
This notebook covers fundamental PyTorch concepts including tensor creation, operations, and neural network layers.

In [3]:
!pip install torch --index-url https://download.pytorch.org/whl/cpu

Looking in indexes: https://download.pytorch.org/whl/cpu


## Imports
Import the torch library for tensor operations.

In [1]:
import torch

## Creating Tensors
A tensor is PyTorch's fundamental data structure. Here we create a 1D tensor (vector) from a Python list.

In [18]:
my_list = [1, 2, 3 , 4, 5]
my_tensor = torch.tensor(my_list, dtype=torch.float32)
my_tensor

tensor([1., 2., 3., 4., 5.])

## Tensor Properties: Shape
Check the shape of the tensor. Shape describes the dimensions and size along each dimension.

In [19]:
my_tensor.shape

torch.Size([5])

## Tensor Properties: Data Type
Check the data type of tensor elements. We used float32, which is common for neural networks.

In [20]:
my_tensor.dtype

torch.float32

## Tensor Operations: Matrix Multiplication
Create 2D tensors (matrices) and perform matrix multiplication using the @ operator.

In [24]:
my_tensor1 = torch.tensor([[1, 2, ],
                            [4, 5, ]])

my_tensor2 = torch.tensor([[5, 6, ],
                            [8, 9, ]]
                            )

print(my_tensor1 @ my_tensor2)

tensor([[21, 24],
        [60, 69]])


## Neural Network Layers
Introduce neural network building blocks. Here we create a Linear layer (fully connected) that transforms 5 input features to 3 output features.

In [2]:
import torch.nn as nn
input_tensor = torch.tensor([[1, 2, 3, 4, 5]], dtype=torch.float32)
linear_layer = nn.Linear(in_features=5, out_features=3)
output_tensor = linear_layer(input_tensor) 
output_tensor

tensor([[4.4248, 1.3771, 4.0669]], grad_fn=<AddmmBackward0>)

A linear (fully connected) layer performs the transformation:
$$\text{output} = \text{input} \cdot \mathbf{W}^T + \mathbf{b}$$


In [30]:
linear_layer.weight

Parameter containing:
tensor([[-0.2840, -0.2452, -0.2679,  0.0188, -0.2418],
        [-0.3697, -0.1334, -0.2314,  0.0674,  0.2665],
        [ 0.2475, -0.1117, -0.3532, -0.1629, -0.0925]], requires_grad=True)

In [31]:
linear_layer.bias

Parameter containing:
tensor([ 0.3635,  0.3425, -0.0706], requires_grad=True)

#### Linear Layer: Neurons and Parameters
Understanding the structure of a neural network layer requires knowing:
- **Number of neurons (output units)**: Determines output dimension
- **Total parameters**: Number of weights and biases to learn


In [3]:
model = nn.Sequential(nn.Linear(in_features=5, out_features=3),
                      nn.Linear(in_features=3, out_features=2),
                      nn.Linear(in_features=2, out_features=2)
                      )

> layers whithin sequential layers are hidden layers

- so first layer have 3 neuron and each neuron have 5+1 parameter = 18. 
- second layer have 2 neurons and each neuron have 3+1 parameter = 8.
- third layer have 2 neuron and each  neuron have 2+1 parameter = 6
- so total learnable parameter count = 32

In [4]:
total = 0
for parameter in model.parameters():
    total += parameter.numel()
print(total)

32


### Activate Functions
it add non linearity to the network
- sigmoid for binary classification (range between 0-1)
- softmax for multi-class classification

In [6]:
new_model = nn.Sequential(nn.Linear(in_features=5, out_features=3),
                      nn.Linear(in_features=3, out_features=2),
                      nn.Linear(in_features=2, out_features=1),
                      nn.Sigmoid()
                      )
new_model

Sequential(
  (0): Linear(in_features=5, out_features=3, bias=True)
  (1): Linear(in_features=3, out_features=2, bias=True)
  (2): Linear(in_features=2, out_features=1, bias=True)
  (3): Sigmoid()
)

In [8]:
new_model_1 = nn.Sequential(nn.Linear(in_features=5, out_features=3),
                      nn.Linear(in_features=3, out_features=2),
                      nn.Linear(in_features=2, out_features=1),
                      nn.Softmax(dim=-1) #indicate softmax is added to last dimention
                      )
new_model_1

Sequential(
  (0): Linear(in_features=5, out_features=3, bias=True)
  (1): Linear(in_features=3, out_features=2, bias=True)
  (2): Linear(in_features=2, out_features=1, bias=True)
  (3): Softmax(dim=-1)
)

### Forward Passing 

input data flows throught layers & final layer generate output based on weight and bias

#### one-hot encording 
(use to convert an integer y into tensor of 0 and 1s)



In [9]:
import torch.nn.functional as F

F.one_hot(torch.tensor([0]),num_classes=3)

tensor([[1, 0, 0]])

In [10]:
F.one_hot(torch.tensor([1]),num_classes=3)

tensor([[0, 1, 0]])

In [11]:
F.one_hot(torch.tensor([2]),num_classes=3)

tensor([[0, 0, 1]])

### Cross-Entropy Loss

In [13]:
from torch.nn import CrossEntropyLoss

scores = torch.tensor([-5.2, 4.6, 0.8])
one_hot_target = torch.tensor([1, 0, 0])

loss = CrossEntropyLoss()
loss(scores.double(), one_hot_target.double())
                       

tensor(9.8222, dtype=torch.float64)

### Convex & non-Convex Functions

Convex function have one minimum and non-convex functions have multiple minimums

### Backpropergation

when we start training of a model the weight and bias are randomly assigns so backpropergaida is used to update the weight and bias to miimise the loss function

In [14]:
test_model = nn.Sequential(
    nn.Linear(16, 8),
    nn.Linear(8, 4),
    nn.Linear(4, 2)
)

# Input: batch of 5 samples, each with 16 features
x = torch.randn(5, 16)

# Target: class labels (0 or 1)
target = torch.tensor([0, 1, 0, 1, 1])

# Forward pass
prediction = test_model(x)

# Loss function
criterion = nn.CrossEntropyLoss()

# Compute loss
loss = criterion(prediction, target)

# Backpropagation
loss.backward()

### Gradient Descant 

it use for non-convolex functions