# PyTorch Basics Tutorial
This notebook covers fundamental PyTorch concepts including tensor creation, operations, and neural network layers.

In [3]:
!pip install torch --index-url https://download.pytorch.org/whl/cpu

Looking in indexes: https://download.pytorch.org/whl/cpu


## Imports
Import the torch library for tensor operations.

In [4]:
import torch

## Creating Tensors
A tensor is PyTorch's fundamental data structure. Here we create a 1D tensor (vector) from a Python list.

In [18]:
my_list = [1, 2, 3 , 4, 5]
my_tensor = torch.tensor(my_list, dtype=torch.float32)
my_tensor

tensor([1., 2., 3., 4., 5.])

## Tensor Properties: Shape
Check the shape of the tensor. Shape describes the dimensions and size along each dimension.

In [19]:
my_tensor.shape

torch.Size([5])

## Tensor Properties: Data Type
Check the data type of tensor elements. We used float32, which is common for neural networks.

In [20]:
my_tensor.dtype

torch.float32

## Tensor Operations: Matrix Multiplication
Create 2D tensors (matrices) and perform matrix multiplication using the @ operator.

In [24]:
my_tensor1 = torch.tensor([[1, 2, ],
                            [4, 5, ]])

my_tensor2 = torch.tensor([[5, 6, ],
                            [8, 9, ]]
                            )

print(my_tensor1 @ my_tensor2)

tensor([[21, 24],
        [60, 69]])


## Neural Network Layers
Introduce neural network building blocks. Here we create a Linear layer (fully connected) that transforms 5 input features to 3 output features.

In [25]:
import torch.nn as nn
input_tensor = torch.tensor([[1, 2, 3, 4, 5]], dtype=torch.float32)
linear_layer = nn.Linear(in_features=5, out_features=3)
output_tensor = linear_layer(input_tensor) 
output_tensor

tensor([[ 1.3477,  3.5092, -2.7345]], grad_fn=<AddmmBackward0>)

A linear (fully connected) layer performs the transformation:
$$\text{output} = \text{input} \cdot \mathbf{W}^T + \mathbf{b}$$


In [26]:
linear_layer.weight

Parameter containing:
tensor([[-0.1664,  0.2784,  0.3023,  0.1654, -0.1657],
        [-0.4453, -0.0189,  0.3192,  0.2357,  0.4187],
        [-0.2852, -0.0546,  0.2928, -0.4301, -0.3192]], requires_grad=True)

In [27]:
linear_layer.bias

Parameter containing:
tensor([ 0.2172, -0.0019,  0.0980], requires_grad=True)